// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBz9EU2oDD-txtHl_1OoEeNfmFLYzC00',
    appId: '1:178713122492:web:01443da6ca19946ad9a2b9',
    messagingSenderId: '178713122492',
    projectId: 'women-safety-app-a01da',
    authDomain: 'women-safety-app-a01da.firebaseapp.com',
    storageBucket: 'women-safety-app-a01da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBot2Hsh8orYjpHEPlisd4O4dg10g4Xh0c',
    appId: '1:178713122492:android:f2f8dd3dc76104bed9a2b9',
    messagingSenderId: '178713122492',
    projectId: 'women-safety-app-a01da',
    storageBucket: 'women-safety-app-a01da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGevZ1ScbclSK5w_8hUmCma9xRUeUnEt8',
    appId: '1:178713122492:ios:06956a051dee9156d9a2b9',
    messagingSenderId: '178713122492',
    projectId: 'women-safety-app-a01da',
    storageBucket: 'women-safety-app-a01da.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGevZ1ScbclSK5w_8hUmCma9xRUeUnEt8',
    appId: '1:178713122492:ios:06956a051dee9156d9a2b9',
    messagingSenderId: '178713122492',
    projectId: 'women-safety-app-a01da',
    storageBucket: 'women-safety-app-a01da.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANBz9EU2oDD-txtHl_1OoEeNfmFLYzC00',
    appId: '1:178713122492:web:4213eb7b3a2c2511d9a2b9',
    messagingSenderId: '178713122492',
    projectId: 'women-safety-app-a01da',
    authDomain: 'women-safety-app-a01da.firebaseapp.com',
    storageBucket: 'women-safety-app-a01da.firebasestorage.app',
  );
}
